In [1]:
import torch

x = torch.rand(5, 5, requires_grad=True)
x

tensor([[0.1998, 0.6415, 0.4868, 0.2415, 0.1884],
        [0.8156, 0.2805, 0.1623, 0.3704, 0.1894],
        [0.7526, 0.0861, 0.4795, 0.3646, 0.1889],
        [0.3041, 0.7529, 0.0837, 0.6126, 0.5756],
        [0.0023, 0.0927, 0.3099, 0.1626, 0.0282]], requires_grad=True)

In [2]:
y = torch.rand(5, 5, requires_grad=True)
y

tensor([[0.8828, 0.6789, 0.8045, 0.5332, 0.0758],
        [0.9217, 0.6291, 0.4867, 0.5354, 0.9488],
        [0.1766, 0.8103, 0.6695, 0.6990, 0.5246],
        [0.0974, 0.2579, 0.5234, 0.7111, 0.2593],
        [0.3291, 0.2487, 0.6341, 0.6397, 0.6478]], requires_grad=True)

In [3]:
z = torch.sum(x + y)
z

tensor(22.0978, grad_fn=<SumBackward0>)

In [4]:
z.backward()

In [5]:
print(x.grad, y.grad)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [6]:
x = torch.rand(5, 5, requires_grad=True)
y = torch.rand(5, 5, requires_grad=True)
z = x**2 + y**3
z

tensor([[0.3309, 0.4482, 0.9689, 0.2667, 1.6697],
        [0.5053, 0.3102, 0.1844, 0.2808, 0.6969],
        [0.0743, 0.6151, 1.0943, 1.0057, 0.8946],
        [0.9073, 1.0124, 1.0703, 0.0037, 0.2410],
        [1.0659, 0.6137, 0.0523, 0.0647, 0.0047]], grad_fn=<AddBackward0>)

In [7]:
z.backward(torch.ones_like(x))
print(x.grad)

tensor([[1.0536, 1.3230, 1.6400, 0.1342, 1.8366],
        [0.5452, 1.0138, 0.8346, 1.0489, 0.9843],
        [0.5433, 1.5585, 1.1012, 1.3954, 0.4691],
        [1.4949, 1.5449, 0.8694, 0.1217, 0.9486],
        [1.9495, 0.8899, 0.4488, 0.5035, 0.1359]])


In [8]:
with torch.no_grad():
    print((x + y**2).requires_grad)

False
