In [1]:
import torch
import numpy as np

torch.__version__

'1.1.0'

In [2]:
x=torch.rand(2,3)
x

tensor([[0.5464, 0.6503, 0.9355],
        [0.3235, 0.0595, 0.7541]])

In [3]:
print(x.shape)
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [4]:
y=torch.rand(2,3,4,5)
y.size()
y

tensor([[[[0.2639, 0.3206, 0.2164, 0.8237, 0.9334],
          [0.8933, 0.7950, 0.1476, 0.5742, 0.4237],
          [0.8848, 0.8323, 0.4403, 0.4759, 0.3147],
          [0.1761, 0.4287, 0.8206, 0.2425, 0.2189]],

         [[0.0346, 0.6380, 0.1530, 0.1188, 0.2477],
          [0.4994, 0.0293, 0.9826, 0.4746, 0.3264],
          [0.5746, 0.9102, 0.9115, 0.3174, 0.5600],
          [0.8950, 0.0696, 0.0727, 0.1658, 0.3457]],

         [[0.1027, 0.1243, 0.5654, 0.2944, 0.6112],
          [0.4165, 0.6369, 0.5389, 0.7398, 0.7339],
          [0.4632, 0.2499, 0.2002, 0.0746, 0.5951],
          [0.9445, 0.8097, 0.3739, 0.7672, 0.7438]]],


        [[[0.7821, 0.3943, 0.7961, 0.5599, 0.4588],
          [0.4936, 0.9491, 0.0142, 0.0374, 0.3045],
          [0.4190, 0.8584, 0.1282, 0.0718, 0.6540],
          [0.2295, 0.7082, 0.4418, 0.7100, 0.8594]],

         [[0.8689, 0.0043, 0.7459, 0.6294, 0.6230],
          [0.5131, 0.5199, 0.1412, 0.4189, 0.0732],
          [0.7016, 0.6248, 0.3410, 0.2094, 0.1151],
  

In [5]:
scalar=torch.tensor(3.1433223)
print(scalar)
scalar.size()

tensor(3.1433)


torch.Size([])

In [6]:
scalar.item()

3.143322229385376

In [7]:
tensor = torch.tensor([3.1433223])
print(tensor)
tensor.size()

tensor([3.1433])


torch.Size([1])

In [8]:
tensor.item()

3.143322229385376

In [9]:
long = tensor.long()
long

tensor([3])

In [11]:
torch_a = torch.from_numpy(numpy_a)
torch_a

tensor([[ 1.9249,  0.3216],
        [-1.0659, -2.3552],
        [-0.4068,  0.9631]])

In [12]:
cpu_a = torch.rand(4,3)
cpu_a.type()

'torch.FloatTensor'

In [13]:
gpu_a = cpu_a.cuda()
gpu_a.type()

'torch.cuda.FloatTensor'

In [14]:
cpu_b = gpu_a.cpu()
cpu_b.type()

'torch.FloatTensor'