In [1]:
import torch
import torch.nn as nn

torch.__version__

'1.1.0'

In [2]:
import torch.nn.functional as F

In [7]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()

        self.conv1 = nn.Conv2d(1, 6, 3)
        self.fc1 = nn.Linear(1350, 10)

    def forward(self, x):
        print(x.size())

        x = self.conv1(x)
        x = F.relu(x)
        print(x.size())
        x = F.max_pool2d(x, (2, 2))
        x = F.relu(x)
        print(x.size())
        x = x.view(x.size()[0], -1)
        print(x.size())
        x = self.fc1(x)
        return x


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=1350, out_features=10, bias=True)
)


In [4]:
for parameters in net.parameters():
    print(parameters)

Parameter containing:
tensor([[[[-0.0484, -0.0179,  0.0531],
          [-0.2766, -0.1878,  0.0702],
          [ 0.1527, -0.0881, -0.1994]]],


        [[[ 0.0069,  0.1667, -0.1013],
          [-0.0577,  0.1964, -0.2233],
          [-0.2063, -0.3229, -0.2016]]],


        [[[ 0.1181, -0.2846, -0.0360],
          [-0.2851, -0.2240,  0.0684],
          [ 0.0102, -0.0923,  0.2033]]],


        [[[ 0.0609, -0.1275,  0.1387],
          [ 0.3271, -0.2300,  0.2561],
          [-0.0838, -0.1577, -0.0099]]],


        [[[ 0.0863,  0.1346,  0.1143],
          [ 0.0601, -0.2091, -0.1526],
          [ 0.1382, -0.1270, -0.0016]]],


        [[[ 0.2922,  0.0124, -0.0741],
          [ 0.0030,  0.2455, -0.1240],
          [ 0.2065,  0.1206,  0.2830]]]], requires_grad=True)
Parameter containing:
tensor([-0.3309, -0.0776, -0.3165, -0.1311, -0.1260, -0.0425],
       requires_grad=True)
Parameter containing:
tensor([[-0.0028,  0.0050,  0.0071,  ...,  0.0055,  0.0132,  0.0127],
        [ 0.0041,  0.0253,  0

In [5]:
for name, parameters in net.named_parameters():
    print(name, ':', parameters.size())

conv1.weight : torch.Size([6, 1, 3, 3])
conv1.bias : torch.Size([6])
fc1.weight : torch.Size([10, 1350])
fc1.bias : torch.Size([10])


In [8]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
out.size()

torch.Size([1, 1, 32, 32])
torch.Size([1, 6, 30, 30])
torch.Size([1, 6, 15, 15])
torch.Size([1, 1350])


torch.Size([1, 10])

In [9]:
input.size()

torch.Size([1, 1, 32, 32])

In [10]:
net.zero_grad()
out.backward(torch.ones(1, 10))

In [12]:
y = torch.arange(0, 10).view(1, 10).float()
criterion = nn.MSELoss()
loss = criterion(out, y)
print(loss.item())

30.07500648498535


In [13]:
import torch.optim

In [14]:
out = net(input)
criterion = nn.MSELoss()
loss = criterion(out, y)
optimizer = torch.optim.SGD(net.parameters(), lr=0.01)
optimizer.zero_grad()
loss.backward()

optimizer.step()

torch.Size([1, 1, 32, 32])
torch.Size([1, 6, 30, 30])
torch.Size([1, 6, 15, 15])
torch.Size([1, 1350])
